spring:
   profiles:
    active: -dev

---
#端口号
server:
  port: 8090

#应用名称
spring:
 profiles: dev  #开发环境
 application:
  name: eureka-server

eureka:
  instance:
   hostname: localhost

  client:
   register-with-eureka: false # 代表不向注册中心注册自己
   fetch-registry: false # 维护服务实例，不需要检索服务

#eureka监控平台地址
   serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    
---
#端口号
server:
  port: 8091

#应用名称
spring:
 profiles: test  #测试环境
 application:
  name: eureka-server1

eureka:
  instance:
   hostname: localhost

  client:
   register-with-eureka: false # 代表不向注册中心注册自己
   fetch-registry: false # 维护服务实例，不需要检索服务

#eureka监控平台地址
   serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
